import os
import hashlib
import json
from datetime import datetime, timezone
import requests
from PIL import Image
import streamlit as st
from io import BytesIO

# --- App configuration ---
st.set_page_config(
    page_title="AI Agriculture & Environment Intelligence",
    layout="centered",
    initial_sidebar_state="auto"
)

# --- Simple translations (dictionary-based fallback) ---
TRANSLATIONS = {
    "en": {
        "app_title": "AI Agriculture & Environment Intelligence",
        "upload_prompt": "Upload crop or pest photo (JPG, PNG)",
        "analyze_btn": "Analyze Image",
        "detected_issue": "Detected Issue / Disease",
        "confidence": "Confidence",
        "reasoning": "Reasoning",
        "limitations": "Limitations",
        "expert_warning": "⚠️ EXPERT WARNING",
        "advisory_tab": "Weather-Aware Advisory Chat",
        "diagnosis_tab": "Image Diagnosis",
        "location_label": "Your Location (district/village)",
        "fetch_weather": "Fetch Weather & Start Chat",
        "chat_placeholder": "Type your question about crops, soil, or waste...",
        "send": "Send",
        "clear": "Clear",
        "no_image": "No image uploaded yet.",
        "analysis_by": "Analysis generated by simulated model",
        "limitations_text": "This automated assessment is advisory only. For complex cases, contact a certified agronomist.",
        "weather_unavailable": "Weather data unavailable — showing sample values.",
        "language_label": "Select Language",
    },
    "hi": {
        "app_title": "एआई कृषि और पर्यावरण इंटेलिजेंस",
        "upload_prompt": "फसल या कीट की फोटो अपलोड करें (JPG, PNG)",
        "analyze_btn": "इमेज विश्लेषण करें",
        "detected_issue": "पहचाना गया समस्या / रोग",
        "confidence": "विश्वास स्तर",
        "reasoning": "तर्क",
        "limitations": "सीमाएँ",
        "expert_warning": "⚠️ विशेषज्ञ चेतावनी",
        "advisory_tab": "मौसम-संबंधी सलाह चैट",
        "diagnosis_tab": "इमेज निदान",
        "location_label": "आपका स्थान (ज़िला/ग्राम)",
        "fetch_weather": "मौसम प्राप्त करें और चैट शुरू करें",
        "chat_placeholder": "फ़सलों, मिट्टी, या कचरे के बारे में प्रश्न लिखें...",
        "send": "भेजें",
        "clear": "साफ़ करें",
        "no_image": "कोई इमेज अपलोड नहीं हुई है।",
        "analysis_by": "सिम्युलेटेड मॉडल द्वारा विश्लेषण",
        "limitations_text": "यह स्वचालित आकलन केवल सलाहमूलक है। जटिल मामलों में प्रमाणित कृषि विशेषज्ञ से संपर्क करें।",
        "weather_unavailable": "मौसम डेटा उपलब्ध नहीं — नमूना मान दिखा रहे हैं।",
        "language_label": "भाषा चुनें",
    },
    "te": {
        "app_title": "ఏఐ వ్యవసాయ మరియు పర్యావరణ ఇంటెలిజెన్స్",
        "upload_prompt": "పంట లేదా పరాన్నీ ఫోటో అప్‌లోడ్ చేయండి (JPG, PNG)",
        "analyze_btn": "ఫోటో విశ్లేషణ",
        "detected_issue": "పరిశీలించిన సమస్య / రోగం",
        "confidence": "నమ్మక స్థాయి",
        "reasoning": "తర్కం",
        "limitations": " పరిమితులు",
        "expert_warning": "⚠️ నిపుణ హెచ్చరిక",
        "advisory_tab": "వాతావరణ-ఆధారిత సలహా చాట్",
        "diagnosis_tab": "ఇమేజ్ నిర్ధారణ",
        "location_label": "మీ స్థలం (జిల్లా/గ్రామం)",
        "fetch_weather": "వెదర్ పొంది చాట్ ప్రారంభించండి",
        "chat_placeholder": "పంటలు, మట్టి లేదా వ్యర్థాల గురించి మీ ప్రశ్న ఇక్కడ టైప్ చేయండి...",
        "send": "పంపండి",
        "clear": "స్వచ్ఛం",
        "no_image": "ఇమేజ్ అప్‌లోడ్ చేయబడలేదు.",
        "analysis_by": "సిమ్యులేటెడ్ మోడల్ ద్వారా విశ్లేషణ",
        "limitations_text": "ఈ ఆటోమేటెడ్ అంచనా సూచనాత్మకమే. క్లిష్ట కేసులకి ప్రత్యేక వ్యవసాయ నిపుణుడిని సంప్రదించండి.",
        "weather_unavailable": "వాతావరణ సమాచారం లభించలేదు — నమూనా విలువలు చూపిస్తున్నాము.",
        "language_label": "భాషను ఎంచుకోండి",
    }
}


def t(key: str, lang: str = "en"):
    return TRANSLATIONS.get(lang, TRANSLATIONS["en"]).get(key, key)


# --- Styling for mobile-first layout ---
def inject_css():
    st.markdown(
        """
        <style>
        /* Safe layout wrapper overrides using modern data attributes */
        [data-testid="stMainBlockContainer"] {
            max-width: 760px !important;
            margin: auto;
            background: #ffffff;
            border-radius: 12px;
            padding: 2rem 1.5rem !important;
            box-shadow: 0 2px 12px rgba(0,0,0,0.04);
        }
        [data-testid="stAppViewContainer"] {
            background: linear-gradient(180deg, #f6fffa 0%, #ffffff 100%);
        }
        [data-testid="stSidebar"] {
            background-color: #f1fff6 !important;
        }
        /* Fluid touch responsive targets for mobile browser views */
        .stButton>button {
            background-color: #2e7d32 !important;
            color: white !important;
            border-radius: 8px !important;
            width: 100%;
        }
        img {
            max-width: 100%;
            height: auto;
            border-radius: 8px;
        }
        </style>
        """,
        unsafe_allow_html=True,
    )


inject_css()

# --- Initialize session states safely ---
if 'chat_history' not in st.session_state:
    st.session_state['chat_history'] = []
if 'weather_info' not in st.session_state:
    st.session_state['weather_info'] = None
if 'location_name' not in st.session_state:
    st.session_state['location_name'] = ""
if 'analysis_result' not in st.session_state:
    st.session_state['analysis_result'] = None

# --- Sidebar: language selection ---
lang = st.sidebar.selectbox("Language / भाषा / భాష", options=["en", "hi", "te"], format_func=lambda x: {
    "en": "English",
    "hi": "हिन्दी",
    "te": "తెలుగు"
}[x])

st.markdown(f"<h1 style='color:#1b5e20; margin-top:0;'>{t('app_title', lang)}</h1>", unsafe_allow_html=True)

# Navigation tabs
tab_labels = [t('diagnosis_tab', lang), t('advisory_tab', lang)]
tab1, tab2 = st.tabs(tab_labels)


# --- Helper: image analysis (simulated) ---
def get_red_blight_analysis(img: Image.Image):
    """
    Analyzes crop image focusing on Red Blight of Tomato.
    """
    # Force the disease to Red Blight for the simulation
    name = "Red Blight of Tomato"
    
    # Generate a dummy confidence based on image properties
    confidence = 85 + (len(img.tobytes()) % 15)
    
    # Specific reasoning for Red Blight
    reasoning = (
        "The image displays necrotic lesions with concentric rings and chlorotic halos, "
        "which are primary visual indicators characteristic of Red Blight in tomatoes."
    )
    
    # Limitations are strictly preserved as per your requirement
    limitations = "Automated assessments cannot substitute lab diagnostic criteria or physical sample testing by an agronomist."
    
    return {
        "disease": name,
        "confidence": f"{confidence}%",
        "reasoning": reasoning,
        "limitations": limitations,
        "note": t('analysis_by', lang)
    }


# --- Geocoding (Nominatim) ---
def geocode_place(place: str):
    if not place:
        return None
    try:
        url = "https://nominatim.openstreetmap.org/search"
        params = {"q": place, "format": "json", "limit": 1}
        headers = {"User-Agent": "AI-Agri-App-Fix/1.0"}
        resp = requests.get(url, params=params, headers=headers, timeout=8)
        resp.raise_for_status()
        data = resp.json()
        if not data:
            return None
        return float(data[0]['lat']), float(data[0]['lon'])
    except Exception:
        return None


# --- Fetch weather (Open-Meteo) ---
def fetch_weather(lat: float, lon: float):
    try:
        url = "https://api.open-meteo.com/v1/forecast"
        params = {
            "latitude": lat,
            "longitude": lon,
            "current_weather": True,
            "hourly": "relativehumidity_2m,precipitation",
            "timezone": "auto"
        }
        resp = requests.get(url, params=params, timeout=8)
        resp.raise_for_status()
        payload = resp.json()
        
        current = payload.get('current_weather', {})
        hourly = payload.get('hourly', {})
        times = hourly.get('time', [])
        hums = hourly.get('relativehumidity_2m', [])
        precs = hourly.get('precipitation', [])
        
        # FIX: Open-Meteo returns hourly array indexes cleanly sliced as 'YYYY-MM-DDTHH:00'
        # Construct clean target comparison to find accurate current hour parameters
        now_hour_str = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:00")
        
        humidity = None
        rainfall = None
        
        if times:
            try:
                idx = times.index(now_hour_str)
                humidity = hums[idx] if hums else None
                rainfall = precs[idx] if precs else None
            except ValueError:
                # Safe operational fallbacks
                humidity = hums[0] if hums else None
                rainfall = precs[0] if precs else None
        
        return {
            'temperature': current.get('temperature'),
            'windspeed': current.get('windspeed'),
            'weathercode': current.get('weathercode'),
            'humidity': humidity,
            'rainfall': rainfall
        }
    except Exception:
        return None


# --- Advisory chat logic (simple rule-based) ---
def generate_advice(question: str, weather_info: dict, location: str):
    q = question.lower()
    parts = []
    
    if weather_info:
        temp = weather_info.get('temperature')
        hum = weather_info.get('humidity')
        rain = weather_info.get('rainfall')
        if temp is not None:
            if temp >= 35:
                parts.append("High temperature: prioritize mulching and irrigation during cooler hours.")
            elif temp <= 10:
                parts.append("Low temperature: protect sensitive crops from cold; apply coverings at night if needed.")
        if hum is not None:
            if hum >= 80:
                parts.append(
                    "High humidity: watch for fungal diseases; ensure good airflow and avoid overhead watering.")
            elif hum <= 30:
                parts.append("Low humidity: increase irrigation frequency and use anti-transpirants if available.")
        if rain is not None and rain > 2:
            parts.append(
                "Recent rainfall: delay fungicide application until leaves dry; check drainage in low-lying areas.")
    else:
        parts.append(t('weather_unavailable', lang))
    
    if any(k in q for k in ["soil", "ph", "fertil", "nutrient"]):
        parts.append(
            "Soil test recommended: apply NPK balancing compounds. For apparent nitrogen stress, deploy organic compost.")
    elif any(k in q for k in ["waste", "trash", "compost"]):
        parts.append(
            "Utilize structured compost bins locally; do not burn remaining straw residues to prevent nutrient volatilization.")
    elif any(k in q for k in ["pest", "aphid", "insect", "worm"]):
        parts.append(
            "Deploy chromatic yellow sticky traps. Introduce neem extracts early before choosing intensive chemical options.")
    else:
        parts.append("General Advisory: Maintain sound crop rotation schemes and keep drainage pathways clean.")
    
    reply = f"**Location:** {location if location else 'Unspecified'}\n"
    if weather_info and weather_info.get('temperature') is not None:
        reply += f"**Current Environment:** {weather_info.get('temperature')}°C"
        if weather_info.get('humidity') is not None:
            reply += f" | Humidity: {weather_info.get('humidity')}%"
        if weather_info.get('rainfall') is not None:
            reply += f" | Rainfall: {weather_info.get('rainfall')}mm"
        reply += "\n\n"
    
    reply += "\n".join(parts)
    return reply


# --- Module A: Image-Based Crop & Pest Diagnosis ---
with tab1:
    st.subheader(t('diagnosis_tab', lang))
    uploaded = st.file_uploader(t('upload_prompt', lang), type=["jpg", "jpeg", "png"])
    
    if uploaded is None:
        st.info(t('no_image', lang))
        st.session_state['analysis_result'] = None
    else:
        try:
            image = Image.open(uploaded).convert('RGB')
            st.image(image, use_container_width=True)  # FIX: Modern non-deprecated parameter
            
            if st.button(t('analyze_btn', lang)):
                with st.spinner('Analyzing...'):
                    # Update to call the new logic
                    st.session_state['analysis_result'] = get_red_blight_analysis(image)
            
            # Persist evaluation visual elements cleanly across loop executions
            if st.session_state['analysis_result']:
                res = st.session_state['analysis_result']
                st.success(res['disease'])
                st.markdown(f"**{t('detected_issue', lang)}:** {res['disease']}")
                st.markdown(f"**{t('confidence', lang)}:** {res['confidence']}")
                st.markdown(f"**{t('reasoning', lang)}:** {res['reasoning']}")
                st.markdown(f"**{t('limitations', lang)}:** {res['limitations']}")
                st.warning(f"{t('expert_warning', lang)}: {t('limitations_text', lang)}")
                st.caption(res['note'])
        except Exception as e:
            st.error(f"Error processing image: {e}")

# --- Module B: Location & Weather-Aware Advisory Chat ---
with tab2:
    st.subheader(t('advisory_tab', lang))
    
    # Preserve input fields using structural Session State variables
    loc_input = st.text_input(t('location_label', lang), value=st.session_state['location_name'])
    
    if st.button(t('fetch_weather', lang)):
        if loc_input:
            st.session_state['location_name'] = loc_input
            with st.spinner('Syncing local telemetry...'):
                coords = geocode_place(loc_input)
                if coords:
                    lat, lon = coords
                    st.session_state['weather_info'] = fetch_weather(lat, lon)
                else:
                    st.warning(t('weather_unavailable', lang))
                    st.session_state['weather_info'] = {'temperature': 28, 'humidity': 70, 'rainfall': 0}
        else:
            st.session_state['weather_info'] = {'temperature': 28, 'humidity': 70, 'rainfall': 0}
    
    # Render Active Climate Panel if initialized
    if st.session_state['weather_info']:
        w = st.session_state['weather_info']
        st.info(
            f"📍 **{st.session_state['location_name']}** — Temp: {w.get('temperature')}°C | Humidity: {w.get('humidity')}% | Rainfall: {w.get('rainfall')}mm")
    
    st.markdown("---")
    
    # Render historical conversation elements chronologically
    for msg in st.session_state['chat_history']:
        with st.chat_message(msg["role"]):
            st.markdown(msg["content"])
    
    # Conversational interactive input processing
    if user_query := st.chat_input(t('chat_placeholder', lang)):
        with st.chat_message("user"):
            st.markdown(user_query)
        st.session_state['chat_history'].append({"role": "user", "content": user_query})
        
        # Compile response logic
        advice_reply = generate_advice(user_query, st.session_state['weather_info'], st.session_state['location_name'])
        
        with st.chat_message("assistant"):
            st.markdown(advice_reply)
        st.session_state['chat_history'].append({"role": "assistant", "content": advice_reply})
    
    # Clear utility button mapping
    if st.button(t('clear', lang)):
        st.session_state['chat_history'] = []
        st.session_state['weather_info'] = None
        st.session_state['location_name'] = ""
        st.rerun()